services:
  # Frontend (React/Vite app)
  - type: web
    name: vitofe666-auction-invoice-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_KEY
        sync: false
    
  # Backend (Node.js webhook server)
  - type: web
    name: vitofe666-auction-invoice-backend
    env: node
    buildCommand: npm install --prefix ngrok-webhook-nodejs-sample
    startCommand: node ngrok-webhook-nodejs-sample/app.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: XERO_CLIENT_ID
        sync: false
      - key: XERO_CLIENT_SECRET
        sync: false
      - key: XERO_REDIRECT_URI
        sync: false
      - key: XERO_WEBHOOK_KEY
        sync: false